server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5435/cinemabookingdb
spring.datasource.username=cinemabookinguser
spring.datasource.password=cinemabooking123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=cinema-booking-service

# JWT
jwt.secret=cinematrack-super-secret-key-minimum-256-bit-long
jwt.expiration=86400000

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer